### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'get_authed'

### ISSUE THREAD

**Issue by ChillyP** [UltimaHoarder/UltimaScraperAPI#5]
Hey DC,

I seem to be having an issue with the latest commit, seems like its an issue with USAPI

```
PS C:\Users\user\Documents\GitHub\UltimaScraper> poetry run python start_us.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\UltimaScraper\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\user\Documents\GitHub\UltimaScraper\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\Users\user\Documents\GitHub\UltimaScraper\ultima_scraper\ultima_scraper.py", line 52, in start
    await self.start_datascraper(datascraper)
  File "C:\Users\user\Documents\GitHub\UltimaScraper\ultima_scraper\ultima_scraper.py", line 136, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 121, in configure_datascraper_jobs
    paid_contents = await authed.get_paid_content()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 469, in get_paid_content
    content = create_message(final_result, user)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BeqlQt5t-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 15, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
AttributeError: 'dict' object has no attribute 'get_authed'
```

**Comment by akiba-geek** [comment]
https://github.com/DIGITALCRIMINALS/UltimaScraperAPI/blame/7f4e562bd28ee67c8978562b2007dfadf6f21e92/ultima_scraper_api/apis/onlyfans/classes/auth_model.py#L42

Error most likely originates here. What exactly is this trying to do?

**Comment by DIGITALCRIMINALS** [comment]
Error is caused by buying paid content and that user doesn't exist anymore
